ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.ordervschaos.ApplicationKt.module ]
    }
}

database {
    jdbcUrl = "jdbc:postgresql://localhost:5432/ordervschaos"
    jdbcUrl = ${?DATABASE_URL}
    user = "postgres"
    user = ${?DATABASE_USER}
    password = "postgres"
    password = ${?DATABASE_PASSWORD}
    maxPoolSize = 10
}
